apiVersion: v1
kind: ConfigMap
metadata:
  name: user-registration-config
  namespace: user-registration
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/userdb"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
