apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: user-registration
type: Opaque
data:
  # Base64 encoded value of "postgres"
  # To generate: echo -n "postgres" | base64
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=
